### ISSUE TITLE
Suggestion: add force flag to  'depcreate'

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#11]
First day with NuTuX so I might miss something.

Is there an option to force recompile all dependencies plus port even when they are currently installed.

I did not see something like that in:  `cards depcreate`

*Just says: The package  XXX is already installed.*

Cheers
P

**Comment by tnut** [comment]
It's not possible because I have to admit this option is not much  used by the packagers (let says even... never)

**Comment by peter1000** [comment]
Thanks for your explanations.
