### ISSUE TITLE
`cards info pkg` should also output some info even if the pkg is not installed

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#14]
Suggestion: It might be nice if `card info pkgname` outputs also some info even if that pkg is not currently installed: e.g. gimp

```
root [ ~ ]# cards search gimp
(gui-extra) gimp 2.8.16 GNU Image Manipulation Program
root [ ~ ]# 
```

At the moment there is no info for such case.

```
root [ ~ ]# cards info gimp
Retrieve info about the 348 packages: 100 %
root [ ~ ]# 
```

**Comment by tnut** [comment]
you have both options -b and -p for that (port and binary)
      cards info -p gimp
      cards info -b gimp

**Comment by peter1000** [comment]
Thanks a lot :+1: 

BTW: if I write new ports which packages do I not need to add to the dependencies: all from `cards.devel`  I'm bit unsure about that?

**Comment by peter1000** [comment]
```
  cards info -p gimp
  cards info -b gimp
```

Would it make sense to always show the proper info and add one extra info: `INSTALLED: YES/NO`

Just a thought?

**Comment by tnut** [comment]
well I was thinking to keep the cli version of 'cards' simple this info would be more appropriate in flcards (the graphical version)
You have as you can see many other commands list, diff, query, file, etc

**Comment by peter1000** [comment]
So far **cards** seems quite nice :+1: 


**I have one other question:**  in arch linux if I try to install a package it calculates first the dependencies and then it asks if I want to do it: which is very nice.

Does **cards** have something similar for binary packages or any plans for such?

example from arch:

![screen-2016-02-20_13-19-59](https://cloud.githubusercontent.com/assets/6168860/13197464/3c8ebdb0-d7bc-11e5-8bc8-0524e9a724cf.jpg)

**Comment by tnut** [comment]
Cards goes much more far:
- It can tell you at wich level this ports belong (very important to know what are the impacts on packages of higher level)
- it make a difference between a binary deps and a compilation deps (it's really not the same)
- In 99 % of the cases, cards find the binaries deps by itself , yes they is an interresting function in pkginfo (do pkginfo -h and you will discover features you never thougt they could even exist :D )
- when cards pack a new package, it add the runtime deps with the build date of them, makes cards unique in that sence: you make one cards install <whatever>  <whatever> can tell cards "be carefull your gtk version is obsolete, I will update (download it ) at the same time as I install <whatever>
- cards look recursively for deps so no need to specify every single deps in the package you want to build
- last but not least cards level will give you the list of the ports per level
- the way how the collections are organise is I thing the best you can find: I give you TWO exemples
    you are interested in xfce4 ONLY:

   echo "dir /usr/ports/xfce4-extra
   dir /usr/ports/xfce4 /usr/ports/g
   dir /usr/ports/gui
   dir  /usr/ports/cli
   dir  /usr/ports/base
   base /usr/ports/base" > /etc/cards.conf

    you are interested in kde5 ONLY:

   echo "dir /usr/ports/xfce4-extra
   dir /usr/ports/xfce4 /usr/ports/g
   dir /usr/ports/gui
   dir  /usr/ports/cli
   dir  /usr/ports/base
   base /usr/ports/base" > /etc/cards.conf

It means yes the ports of each "collection" are clearly separated whithout overlapping

**Comment by peter1000** [comment]
**librairies** seems that this is not English


 https://github.com/NuTyX/cards/blob/ae6c74e2f2f463bea0699ab2bb43f5daa3df15f2/src/pkginfo.cpp#L368 : ` list all the runtime librairies for the <package>`

**Comment by tnut** [comment]
library ?

**Comment by peter1000** [comment]
noun (plural **libraries**)   http://www.oxforddictionaries.com/us/definition/american_english/library

**Comment by tnut** [comment]
commited

**Comment by peter1000** [comment]
:+1:
