### ISSUE TITLE
Additional Pkgfile Tag: Info

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#15]
Just a question: What do you think of adding one additional Pkgfile tag e.g. **Info** or **Extra Info**

This could be used for additional info like optional dependency in Arch Linux or anything else.

`cards info pkgname` could then display this additional info.

```
# Description:  Hardware detection tool from openSUSE.
# URL:          http://www.opensuse.org/
# Maintainers:  peter1000 <https://github.com/peter1000>
# Packagers:    peter1000 <https://github.com/peter1000>
# Depends on:   git libx86emu
# Info: Some additional info like optional dependency in Arch Linux or anything else.
```

**Comment by tnut** [comment]
we have the <package>.info for this purpose

**Comment by peter1000** [comment]
Sorry I do not understand: `we have the .info for this purpose` do you mean something like:

```
# Description:  Hardware detection tool from openSUSE.
# URL:          http://www.opensuse.org/
# Maintainers:  peter1000 <https://github.com/peter1000>
# Packagers:    peter1000 <https://github.com/peter1000>
# Depends on:   git libx86emu

# .info: Some additional info like optional dependency in Arch Linux or anything else.
```

**Comment by tnut** [comment]
Sorry I mixte up with the name_of_package.README file. I was slowly going away from considering comment information as meta data in the archive. I think, if we want more tag like info it should be define in a variable. Makes life much more easy for the pkgmk script

**Comment by peter1000** [comment]
Thanks for taking the time to reply, I appreciate it.

**Comment by tnut** [comment]
I appreciate very much your interest.

**Comment by peter1000** [comment]
So far it looks good: main problem is probably the lack of documentation :)

Anyway, I will have still have some time 1 or 2 days and then I'm busy for 1-2 weeks.
