### ISSUE TITLE
Feature idea: git source and similar

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#16]
Cards - pkgmk: Feature idea: git source and similar

**Pkgfile**

Currently it seems that for git sources `source=()` is used in in the `build()` function something like `git clone $_source foldername_to_clone_into`

**To avoid re-cloning everything** each time it would be good that a clone is first made in the: `PKGMK_SOURCE_DIR` 

**Currently I do something like**

```
build() {
    # Get the source repo
    if [ -d $PKGMK_SOURCE_DIR/$name ];then
        # Update the repo into $name folder
        cd $PKGMK_SOURCE_DIR/$name && git pull
    else
        # Clone the repo into $name folder
        git clone $_source $PKGMK_SOURCE_DIR/$name
    fi

    cp -r $PKGMK_SOURCE_DIR/$name $SRC/$name
    cd $SRC/$name

   .......... compile
}
```
It would be nice if cards could additionally understand git sources in the `source=() array` similar to e.g. Arch PKGBUILD files.

e.g.
```
source=("foldername_to_clone_into::git+https://github.com/peter1000/$name.git")
```

for more info see <https://www.archlinux.org/pacman/PKGBUILD.5.html#VCS>

**Comment by peter1000** [comment]
If it is ok with you - I can add this feature?

**Comment by tnut** [comment]
Yes go ahead As long you dont break pkgmk

**Comment by peter1000** [comment]
No, I want break it - just add additional features - so it should be completely backwards compatible.

Personally, I prefer a git version source instead of a release tar ball.

**Comment by peter1000** [comment]
## Current plan is to implement this

Sorry it does not fit in the small window: **to read it  is best to copy/past it into an text editor like geany**.

```
INFO: NuTyX-Linux:Pkgfile: source (array) **peter1000** <https://github.com/peter1000> (Feb. 2016) for NuTyX-Linux.

An array of source files required to build the package. This can also be an empty array `source=()`.
To simplify the maintenance of Pkgfiles, use the $name and $version variables when specifying the download location, 
if possible.
Compressed files will be extracted automatically unless `PKGMK_IGNORE_UNPACK="yes"` is set or they are local files 
specified by relative path to the Pkgfile.

It is also possible to change the name of the downloaded file, which is helpful with weird URLs and for handling
multiple source files with the same name.

::1:::::::::::::::::::::::::::: Regular source entries can have two forms:

  1) The syntax is: source=(filename::url)

      The source URL is divided into two components:

          1. `filename` (optional): The new changed name of the downloaded file. `::` is used as separator.
          2. `url:` (required):     A fully-qualified URL (see supported protocols below) or a local file path
                                    which is resolved relative to the directory of the `Pkgfile`.


  Currently supported protocols are: ftp, http, https, file or relative path to local file


::2:::::::::::::::::::::::::::: There is also support using sources downloaded from version control systems (VCS).

  1) The syntax is: source=(directory::url#fragment).

      The source URL is divided into three components:

          1. `directory` (optional): Specifies an alternate directory name to download the VCS source into. 
                                     `::` is used as separator.
          2. `url` (required):       The URL to the VCS repository. This must include the VCS in the URL protocol. 
                                     If the protocol does not include the VCS name, it can be added by prefixing 
                                     the URL with vcs+. For example, using a Git repository over HTTPS would have a 
                                     source URL in the form: `git+https://....`
          3. `fragment` (optional):  Allows specifying a revision number or branch to be checkout from the VCS. 
                                     For example, to checkout a given revision, the source line would have the 
                                     format source=(url#revision=123). `#` is used as separator.

              The available fragments depends on the VCS being used:

                  1. `bzr`: revision (see 'bzr help revisionspec' for details)
                  2. `git`: branch, commit, tag
                  3. `hg`: branch, revision, tag
                  4. `svn`: revision

  Currently supported version control systems are Bazaar, Git, Subversion, and Mercurial.
  For other version control systems, manual cloning of upstream repositories is usually done in the build() function.



::3:::::::::::::::::::::::::::: Local resource files

  NOTE: 
      * A local source file path which is resolved relative to the directory of the `Pkgfile`.
        (MUST NOT start with a backslash `/`).

      1) The syntax is: source=(filename)
      2) The syntax is: source=(resources/filename)



::4:::::::::::::::::::::::::::: EXAMPLES

 LOCAL FILES

source=(test_file)
source=(resources/test_file)


 QUALIFIED URI

  file
source=(file://localhost/usr/ports/personal/patches/test_file)
source=(file:///usr/ports/personal/patches/test_file)

  ftp
source=(ftp://ftp.astron.com/pub/file/file-5.25.tar.gz)
source=(file::ftp://ftp.astron.com/pub/file/file-5.25.tar.gz)

  http
source=(http://tukaani.org/xz/xz-5.2.2.tar.xz)
source=(xz::http://tukaani.org/xz/xz-5.2.2.tar.xz)

  https
source=(xmlto::https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.bz2)
source=(https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.bz2)

 VCS (version control systems)

  GIT
source=(git://github.com/peter1000/linux-helper-install-scripts.git)
source=(git+http://elinks.cz/elinks.git#commit=a3751107033599b835eaafa61177c8d4dda4b7ef)
source=(linux_install_scripts::git+http://github.com/peter1000/linux-helper-install-scripts.git)
source(test::git+https://cgit.freedesktop.org/poppler/test/#commit=0d2bfd4)
source=(git+https://github.com/kaio/ibus-table.git#tag=1.9.11)

  SVN
source=(svn://svn.code.sf.net/p/splix/code/splix#revision=315)
source=(wit::svn+http://opensvn.wiimm.de/wii/trunk/wiimms-iso-tools#revision=6005)

  HG
source=("hg+https://bitbucket.org/ianb/pastedeploy#tag=1.5.2")
source=("pivy::hg+https://bitbucket.org/Coin3D/pivy#tag=pivy-20101207")

  BZR
source=(bzr+lp:~elementary-os/contractor/elementary-contracts)
source=(foomatic_db::bzr+http://bzr.linuxfoundation.org/openprinting/foomatic/foomatic-db/#revision=1295)
```

**Comment by peter1000** [comment]
**just for info:**

I rechecked the need to support the `file://` protocol and **concluded it is not needed.**

REASON: 

1. I scanned all official Nutyx Pkgfile and did not find any use of it in the source=() array
2. I scanned all Arch Linux PKGUILD files (from abs) and did not find any use of it in the source=() array

**Comment by tnut** [comment]
Even then, It's always good to brng new ideas, That's our motor

**Comment by peter1000** [comment]
Making good progress but I think I will have to touch more of the original `pkgmk` code.

**e.g. make_md5sum**: I can not leave it as it is,  because for version controlled sources we can not use this.

Arch-Linux solved this by having an additional corresponding array for the `source`

```
source=(git+https://github.com/kaio/ibus-table.git#tag=1.9.11)
md5sums=('SKIP')
```

But there are more parts like this which I just see as I go through the current code.

---

I think at the moment just skipping  such source (git, svn etc..) is ok but I need to touch more of the code than I thought before.

Because I *REALLY* want and need support for version controlled sources like (git, svn) I will rewrite more of the pkgmk file: if you don't like it there is no problem: I can always patch cards when I install it.

**Comment by peter1000** [comment]
hi @tnut 

I have some thoughts: because as I mentioned in the post above I will have to rewrite a bit more of the `pkgmk` (at least for my own usage) and some thing are just historical which may be 16 years old (copyright starts at 2000).

## My Thoughts

I would like to simplify some of the options (base on my personal usage of Gentoo-Linux and Arch-Linux) but also add new features like mentioned above.


### 1. Support One Download Manager

Use  only `wget` as the required download manager.  see discussion issue #24.

### 2. Archive Compression Format

Currently there are [3 available formats](https://github.com/peter1000/cards/blob/add_PKGMK_COMPRESSION_OPTS/scripts/pkgmk.in#L754) `gz, bz2, xz`  

From your example `pkgmk.conf` is seems that you favour [xz](https://github.com/peter1000/cards/blob/add_PKGMK_COMPRESSION_OPTS/scripts/pkgmk.conf#L49)

*PLAN*: Archive Compression Format **xz**

* `PKGMK_COMPRESS_PACKAGE="yes/no"`:  allows for disabling compression
* `PKGMK_COMPRESSION_OPTS="-9 ---threads=$(getconf _NPROCESSORS_ONLN)"`:  allows for setting faster or better compression and advanced settings

### 3. What do you think?

Maybe some variables should be readonly: e.g.

* [PKGMK_PKGFILE="Pkgfile"](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1473)

Maybe

* `PKGMK_PACKAGE_EXT="cards.tar"`
* `PKGMK_REPO=".PKGREPO"`

**Comment by tnut** [comment]
This Songs very good ideas. About compress Format. I heard about lzip
Format which seems to promess a lot

Totally agreed for the readonly variable. But be Aware, if we want to
interprepret the PKGBUILD file from archlinux, the PKGMK_PKGFILE
<https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1473> should
stay dynamic

2016-02-25 12:32 GMT+01:00 peter1000 <notifications@github.com>:

**Comment by peter1000** [comment]
Thanks, today I will have some more time and hope to do as much as possible: Yes I saw later that you use `PKGMK_PKGFILE` for Arch Builds.


About the Arch support:   I'm not exactly sure what you plan: but

would it not be better to write a converter. I have done a couple of years ago one in python to convert from: `Arch PKBUILD` to [conda](https://github.com/conda/conda) format.

So we could do something similar: **PKGBUILD  -> output NuTyX Pkgfile**

But maybe you plan something different?

**Comment by peter1000** [comment]
Today I will push multiple commits (so it is easier to see the different steps) to one pull-request

**Comment by tnut** [comment]
For you info, Since about a week or so I'm preparing the 8.1 Version of
NuTyX. Everything went quite well except for the package samba. I did post
the issue on BLFS trac System. When I Google the error, it's like I'm the
only one which face this error. I feel sundenly I'm leaving in another
planet. It's really a strange Feeling. I think it's first time this happens
in 10 years. Imagine I have (I think) try all the possibles methods:

-  compileds all thes deps  on 8.0
-  compileds all the deps on 8.1
-  compileds all the deps on a pass1/2 (means a brand New LFS System)

The message error keeps coming.

I'm desparate

Thierry

**Comment by peter1000** [comment]
How could I be of help: If you give me some direction I can look into it?

**Comment by tnut** [comment]
Try on your NuTyX 8.0 to compile samba

2016-02-26 10:19 GMT+01:00 peter1000 <notifications@github.com>:

**Comment by peter1000** [comment]
OK I can do that - let you know a bit later.

**Comment by peter1000** [comment]
Just a thought: is there a way to auto-install all the compile/devel packages:

e.g.: `pkgmk`

```
Checking for gnutls >= 3.0.0s                                                                   : not found 
Checking for gnutls >= 1.4.0 and broken versions                                                : not found 
/var/pkgmk/work/build/src/samba-4.3.3/source4/lib/tls/wscript:37: error: Building the AD DC requires GnuTLS (eg libgnutls-dev, gnutls-devel) for ldaps:// support and for the BackupKey protocol
=======> ERROR: No files found in /var/pkgmk/work/build/pkg...
```

Or do I need to install all them manually?

**Comment by tnut** [comment]
You should do EXACTLY like the readme of any collection says otherwise you run in this kind of trouble forever (dependencies missings)

**Comment by tnut** [comment]
Will update the README to add the procedure like in the others collections and adapt it for cli and gui at least. (base is another Story)

**Comment by peter1000** [comment]
Maybe you could wait until we got the `pkgmk` a bit better sorted out and have added also some additional documentation to the man pages.

**Comment by peter1000** [comment]
Finished: it seems that it build it but I get an error at the end:

`cards create samba`
```
2016-02-26 13:39:48 (1.18 MB/s) - '/tmp/samba-4.2.3.tar.gz.partial' saved [20721283/20721283]

=======> ERROR: samba1442675901x86_64.cards.tar.xz should be remove
=======> ERROR: samba.devel1442675901any.cards.tar.xz should be remove
=======> ERROR: samba.service1442675901any.cards.tar.xz should be remove
=======> ERROR: samba.man1442675901any.cards.tar.xz should be remove
=======> ERROR: samba.doc1442675901any.cards.tar.xz should be remove
=======> ERROR: Remove the binaries first...
cards 1.99.7 create: could not parse /8.0/gui/samba/Pkgfile
root [ ~/extra ]# 

```

But`samba1442675901x86_64.cards.tar.xz` is `9.2MiB`

```
root [ ~/extra ]# ls -l /8.0/gui/samba
total 10140
-rw-rw-r-- 1 1000 1000    2331 Oct 31 13:35 Pkgfile
-rw-rw-r-- 1 1000 1000    6166 Oct 31 13:35 samba.README
-rw-r--r-- 1 root root  256300 Sep 19 15:23 samba.devel1442675901any.cards.tar.xz
-rw-r--r-- 1 root root  118700 Sep 19 15:23 samba.doc1442675901any.cards.tar.xz
-rw-r--r-- 1 root root  386052 Sep 19 15:23 samba.man1442675901any.cards.tar.xz
-rw-r--r-- 1 root root    1404 Sep 19 15:23 samba.service1442675901any.cards.tar.xz
-rw-r--r-- 1 root root 9596432 Sep 19 15:23 samba1442675901x86_64.cards.tar.xz
-rw-rw-r-- 1 1000 1000    2641 Oct 31 13:35 tls-use-gnutls_priority_set_direct.patch
root [ ~/extra ]# 

```

Anyway I will sync as there is a new port version

**Comment by tnut** [comment]
Uses the comand: 

    bash scripts/gui samba

**Comment by tnut** [comment]
Finally found the prob. ... cards is the responsible. I did something really nasty in cards 1.99.6 to 1.99.7. 
I had to take 1.99.5 to make samba compiling again. It means All the changes on pkgmk.in script file since version 1.99.5 have to be review

**Comment by peter1000** [comment]
I see: the pkgmk.in should not be too hard it is only 25 days and a couple of commits.

**Comment by peter1000** [comment]
hi @tnut,

I would suggest that you still merge: <https://github.com/NuTyX/cards/pull/28> because there are also a good number of spelling corrections, documentation improvements etc..

Afterwards one might want to start with the version ` 1.99.5` and check each commit until there problem is found.

just a suggestion (want have much time next week to redo any merge conflicts)

**Comment by peter1000** [comment]
Maybe this helps: a quick look what has changed since 1.99.5: <https://github.com/NuTyX/cards/compare/380599c5f6e71c6fe17433ff164f1e1d4c0f6553...master>

**Comment by peter1000** [comment]
I finished committing to [Multiple commits](https://github.com/NuTyX/cards/pull/28)

**You could merge it because there are currently not merge conflicts.**

Afterwards I will do some more work (tomorrow or Monday) to cleanup some variables and do some documentation etc...

Have a nice weekend

P

**Comment by peter1000** [comment]
In case you are interested: I adapted a handful of packages to use the new: **git source**

[p-diverse](https://github.com/P-NuTyX/p-diverse)

*QUESTION*: is ther a simple command to clean all ports: e.g. remove the downloaded file, the .PKGREPO etc.. so that I can commit it to github - or do I need to do it manually?

**Comment by tnut** [comment]
I'm absolutly shure it's the script pkgmk the responsible. The failure occur in the middle of the compilation of samba at the
+ make line
If I did it manually, they was no issues at all. 

What is quite incredible is that we could compile so many packages without problems

**Comment by tnut** [comment]
About your last question ? That's exactly why you should use the script include in the collection you want to build and follow the README file. For your info, they is even an help command, example for gui collection:

       bash scripts/gui -h

**Comment by peter1000** [comment]
I was mainly considering [my own ports](https://github.com/P-NuTyX/p-diverse) which are not in an official collection.

**Comment by tnut** [comment]
It's not a prob at all. Use the same script and make a link. Have a look how this is done in the scripts directory of any collection (yes it's always the same :)   ...)

**Comment by peter1000** [comment]
What I do not understand: if it is preferred do use `bash scripts` what is the purpose of `cards create`?

**Comment by tnut** [comment]
cards create should be used by the official packagers Pierre-nutyx and me. It build the final package only. All the deps HAVE to be available in binary together with the script you mention. Thats how the final binary are build at least

**Comment by peter1000** [comment]
Thanks for the info (should be added to the documentation) one day ;)
