### ISSUE TITLE
Question: PKGMK_PACKAGE_DIR

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#22]
I noticed already a couple of days ago that setting: **PKGMK_PACKAGE_DIR** seems to have no effect. When I tried Crux I think it did work. 

I just checked Crux and they have set it to `PKGMK_PACKAGE_DIR="$PWD"`

**I'm quite sure that you have good reason** that you set it to **readonly** [here](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1458)

My Question: do you remember why this is **readonly**? I'm asking because I want to use it as a reference to the absolute directory of a Pkgfile - so I need to make sure you had the same idea.

**Comment by tnut** [comment]
yes because cards need to look in the collection/port_name directory to find the binaries. Its for this reason its forbiden to modify this variable anymore

**Comment by peter1000** [comment]
Thanks

I think it would be wise to mention in the documentation (and man page) this difference to: Crux.

**Comment by tnut** [comment]
don't make any change on pkgmk.in until my next commit so to avoid conflict on your side, I'll try to commit it tonight

**Comment by peter1000** [comment]
:+1:  no hurry - with your [previous commit](https://github.com/NuTyX/cards/commit/64c0f4e14a19a4df328421006f980b911709f58f) I've got all what I need for now.
