### ISSUE TITLE
Question: PKGMK_SOURCE_MIRRORS

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#23]
**man pkgmk.conf**

```
       PKGMK_SOURCE_MIRRORS=('STRING')
              Set mirrors to check and download source archives from.
              Default: none
```

What is the idea behind this: are this online mirrors or local file folders? Anyone uses that and give a actual example?

Thanks
P

**Comment by tnut** [comment]
This are online mirrors it will check first this url if the source exist, if not will use the URL from source variable

**Comment by peter1000** [comment]
Thanks
