### ISSUE TITLE
QUESTION: Download client

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#24]
hi @tnut,

Do you think that there is a need to support 2 download clients?

I gathered some info:

**Arch Linux**

* [cURL](https://www.archlinux.org/packages/?sort=&q=curl&maintainer=&flagged=) is in the **core repo**
* [wget](https://www.archlinux.org/packages/?sort=&q=wget&maintainer=&flagged=) in **only** in the  **Extra repo**

Would it not be enough to support only `cURL` Arch Linux seems to favor it?

`cURL` seems to support more protocols (even though this is probably not needed) but is bigger.

Anyway I can seem to see the need to have two of them?

**Comment by tnut** [comment]
A lot of packages are using wget in the build function (for downloading the BLFS scripts for example).
Shure cURL has more possibilities. wget is I beleave more easy to handle in a script. The reason why the command curl is in pkgmk.in is only historical. In the begin of houaphan version wget was in base-extra collection. Only cURL was included in the base collection. 

May be one day we could remove it. It's not the first priority as it would need to review all the concerned recepts

**Comment by peter1000** [comment]
So why not only use the `wget` in the pkgmk file to download: Seems you have removed the `PKGMK_CURL_OPTS` already.

That does not mean that in the `build function` one can not use something else I'm just talking about the pkgmk part. like this one [curl](https://github.com/NuTyX/cards/blob/654a992ff70c79dd762493ed0901126be099a368/scripts/pkgmk.in#L185) does not seem to make much sense if `wget` is installed by default?

Anyway thanks for your clarification. I will use for my addons only `wget`.
