### ISSUE TITLE
Cards depends -p pkg: not showing missing

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#26]
Not sure if I got that right: but it seems that: `cards depends -p pkg` does not show missing dependency ports.

example:

```
root [ /usr/curl ]# cards depends -p gimp
/usr/ports/personal/babl
/usr/ports/personal/gimp
root [ /usr/curl ]# 
```

If I delete port `/usr/ports/personal/babl`

```
root [ /usr/curl ]# cards depends -p gimp
/usr/ports/personal/gimp
root [ /usr/curl ]
```

**Would it not be good** if cards would output something like: [missing port]

```
root [ /usr/curl ]# cards depends -p gimp
/usr/ports/personal/babl [missing port]
/usr/ports/personal/gimp
root [ /usr/curl ]# 
```

**Comment by tnut** [comment]
will have look. But normally we use cards level for this purpose. The option -p is irelevant in depends command cards depends -h
