### ISSUE TITLE
Arch canges all source files to permission: root user & root group

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#34]
Just a thought: when I looked through some code I saw that Arch-Linux changes all source files permissions (Work directory) to  root user & root group.

I did add this in my new additions but wanted to ask if that is OK.

**Comment by tnut** [comment]
Is that really necessary ? If we do so, they will be no possibilities to try a port in a non root account

**Comment by peter1000** [comment]
>Is that really necessary ?

Not sure just saw what Arch Linux does. but see the [Crux Building ports as an unprivileged user ](https://crux.nu/Wiki/FakerootPorts)

**Comment by peter1000** [comment]
The current code suggests and warns: that packages should be build as root: [see](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1576)

```
	if [ "$UID" != "0" ]; then
		warning "Packages should be built as root."
	fi
```

**Comment by peter1000** [comment]
if there are problems we might want to try first this solution:  [Crux Building ports as an unprivileged user ](https://crux.nu/Wiki/FakerootPorts) otherwise just this code has to be commented/removed in the `pkgmk.in`

```
	if (( EUID == 0 )); then
		# change perms of all source files to root user & root group
		chown -R 0:0 "$SRC"
	fi
```

**Comment by tnut** [comment]
Yes I was thinking about the same

2016-03-01 20:32 GMT+01:00 peter1000 <notifications@github.com>:
