### ISSUE TITLE
ARCH i686: add info to documentation / readme

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#35]
I saw still code related to ARCH i686 - but the [documentation says](https://github.com/NuTyX/houaphan)

`NuTyX is a GNU/Linux distribution for 64-bit (x86_64) architecture ...`

**Should the historical  **i686** code parts be remove?***

If so does it still make sense to have binary package file names like

* attr.devel1441742055**x86_64**.cards.tar.xz  
* attr.nl1441742055**any**.cards.tar.xz

**Comment by tnut** [comment]
No and Yes. Documentation should be adjust. Some netbook are 32 bits only

**Comment by tnut** [comment]
My last commit is to give the possibility to install in a "cross Installation" means for ex: The hostmachine is a x86_64 and the "/mnt/sda4" Folder is a arm System. It's now possible to do:

       /mnt/sda4/Tools/bin/pkgadd /mnt/sda4/root/current/base/nutyx1453245645arm7.cards.tar.xz
       nutyx: Architecture is different. If /mnt/sda4 filesystem is a arm7 architecture, everything is OK...

**Comment by peter1000** [comment]
Nice one.
