### ISSUE TITLE
peter1000 plan for next days

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#38]
Just for info that we might not work on the same things:

My plan for today or tomorrow:

* reorganize the: `pkgmk.in` file with the latest additions
* unify some of the code style in  `pkgmk.in`
* add an option to automatically update the **Pkgfile version** when new sources from VCS e.g. git is fetched.

**Comment by tnut** [comment]
Be aware that we have to fix the issue when trying to compile samba. It's ok for me. 

My plan for today: (my wife is away the all day) :)

* start with the www/en/news.html
* start with the www/en/packager.html. Packaging for advanced user, this article will not explain what's a variable ...  but whats are all the rules  for producing a package that can be compiled without problems by a bot ( which is for the moment nothing else then scripts/enter-nutyx)
* fix the issue with cards
* produced a 32bits / 64 bits NuTyX_XXX_8.1-rc1.iso (probably whith both kernel this time. means 4 ISOS)
* when you have review www/en/news.html and www/en/packager.html. I will write the french version of them

I would be glad that you follow the www/en/news.html and www/en/packager.html and review then .

**Comment by peter1000** [comment]
**1**
In case you make a `NuTyX_XXX_8.1-rc1 XFCE.iso`: it would be nice if you write down roughly the steps.

**2**
Today I want have internet for some time but I can check out the documentation you write  later or tomorrow.

**Comment by peter1000** [comment]
Just a thought: maybe before you do: **fix the issue with cards** you could merge first all pull requests. till then I will still commit to it.

**Comment by peter1000** [comment]
Today I will still do some code improvements: and add some functions for automatic version update in the Pkgfile: similar to what Arch linux does.

From tomorrow on I will not have so much time ....

**Comment by tnut** [comment]
Let me know when I can release  1.99.8, make the Archive available and update the binaries

**Comment by peter1000** [comment]
OK I tell you: I think I still would like to finish a couple of things: AND importantly - I guess you should test it thoroughly afterwards ... a lot of things where moved around and I tested it just on very simple examples - do not know NuTyX well enough.

Anyway, at least the old features MUST be working without errors - (no pkg uses the new one ;)

Will tell you later .... when I'm ready

**Comment by peter1000** [comment]
Sorry did not do much today - if you do not mind I still would like to add more support for translation to the pkgmk.in and a couple of other things.

If you are in a hurry a just tag a release ....

**Comment by peter1000** [comment]
To MERGE: 

1. #45 
2.
3.

**Comment by peter1000** [comment]
Last pull request for today: https://github.com/NuTyX/cards/pull/47

The main things are done what I wanted to do: still needs actual checking as much code was added and changed.

Maybe you could use it to build the new 8.1 ?

There are still a lot of open things especially documentation but I thin we write that when I start actually using NuTyX :)
