### ISSUE TITLE
No GCC

### ISSUE THREAD

**Issue by bosko2004** [NuTyX/cards#4]
I like the way nutyx and cards works. But I do not underatand how do packages that are installed with cards and cards itself use gcc when there is no gcc file for execusion(checked with `find`) I wanted to install i3wm from source but it did not work. Error says that there is no acceptable C compiler. That means that I can't install gcc either because it does not have any C compiler. I tried to reinstall the gcc from cards but nothing happened. I Even tried to reinstall nutyx in fixed and rolling version.

**Comment by bosko2004** [comment]
As answerd in telegram chanell cards.devel needs to be installed. Thanks to @spiky

**Comment by tnut** [comment]
Thank you for reporting. 
Some clarifications. As explain in documentation, NuTyX propose packages and sub-packages, where a sub-package belong to groups. Groups are:
- devel
- lib
- man
- doc
- <locale>

To be able to use gcc compiler, you need to install cards.devel. It will bring all the devel packages that are need to make some basic packages.

In the future we plan to have a set of packages call 'devel' or something similar that would integrate all the packages needed for developing.
