### ISSUE TITLE
prepare(): Is supported but never used

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#40]
I saw that a Pkgfile function called `prepare()` will be automatically executed -but I did not find any in the official Pkgfiles.

Just wondering if that info has been forgotten or never mentioned in the documentation.

**Comment by tnut** [comment]
This is a (new) standard function which you can find in PKGBUILD recepts from archlinux. You also find package() and some others (I forgot already)

**Comment by tnut** [comment]
For the documentation, all thoses "tricky" stuffs should go to packager.html
Didn't start yet :(

**Comment by peter1000** [comment]
Ah, it's for the Arch PKGBUILD: I do maintain some Arch packages [ArchLinux_packages_p](https://github.com/peter1000/ArchLinux_packages_p)

**Anyway, in my opinion I would not integrate it directly to cards, I would write a separate converter which outputs proper: NuTyX-Linux Pkgfiles**

Keeps your `cards` code cleaner.


**And than run the converter over the whole: `abs`: which contain all official Arch PKGBUILD**
