### ISSUE TITLE
Question: Exit code, compression

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#44]
just a general question:

**1.**
 do you check the exit code from pkgmk in your C++ code?

Should we keep all those different Exit codes or simplify them for errors: `exit 1` 

**2.**
I mentioned somewhere that at the moment there are 3 compression options for card packages:

https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1086

```
		gz) gzip $PKGMK_COMPRESSION_OPTS $1;;
		bz2) bzip2 $PKGMK_COMPRESSION_OPTS $1;;
		xz)  xz -z $PKGMK_COMPRESSION_OPTS $1;;
```

Most people I know will use only `xz`. Probably a historical leftover. 

Should we simplify it and only use `xz` as default - or no compression. 

Remove the option to choose?

**Comment by tnut** [comment]
1. Yes
2. No

**Comment by peter1000** [comment]
OK I simplify the exit code and keep the compression as it is.
