### ISSUE TITLE
if binary exists and must be removed: why download first the source?

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#46]
Currently: if a binary exists an I run: `# pkgmk`

It downloads first the source and afterwards it stops because of the existing binary file.

```
==> Downloading git into: <linux-helper-install-scripts>
    Cloning git repo <linux-helper-install-scripts>
Cloning into bare repository '/usr/ports/p-diverse/linux-helper-install-scripts/linux-helper-install-scripts'...
remote: Counting objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
==> ERROR: <linux-helper-install-scripts1456859871x86_64.cards.tar.xz> should be removed.

====> ABORTING....
    -> Remove the binaries first...

```

**Would it not be better:** if it first checks if the binary exists and exists immediately?

* also would it make sense to save the existing as a backup and just compile the new one?

Or do I misunderstand here something?

**Comment by tnut** [comment]
Yes, even I don't really remember why binaries are not automatically delete, They should not be delete automaticaly until I remember why :)

**Comment by peter1000** [comment]
OK we just leave it - and maybe the issue open ;)
