### ISSUE TITLE
libpng build failed with the latest pkgmk.in

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#48]
==> Building package: </usr/ports/cli/libpng/libpng1456864826x86_64.cards.tar.xz>
  -> Extracting file with (bsdtar): </sources/libpng-1.6.21.tar.xz>
  -> Extracting file with (gzip): </sources/libpng-1.6.21-apng.patch.gz>
gzip: .gz: No such file or directory
/usr/bin/pkgmk: line 279: local: `/usr/ports/cli/libpng/libpng1456864826x86_64.cards.tar.xz': not a valid identifier
==> ERROR: Building failed: <>

====> ABORTING....
    -> Failed to extract file: </sources/libpng-1.6.21-apng.patch.gz>. SOURCE: http://downloads.sourceforge.net/project/apng/libpng/libpng16/libpng-1.6.21-apng.patch.gz

**Comment by peter1000** [comment]
will look into this

**Comment by peter1000** [comment]
Maybe you can recheck if this fixes it and then close the issue.

BTW: all downloaded archives are automatically extracted: except: PKGMK_IGNORE_UNPACK="yes"
[see info](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L75)

So the patch line would need to be adjusted. Maybe it would be a nice idea to add an option to define per source entry if it should be extracted or not - I will look into this later

**Comment by peter1000** [comment]
UPDATE: after merging #53 one could also keep the Pkgbuild and add only NOEXTRACT to the patch file so this are the 2 options:

1. **My preferred variation for such Pkgbuild**

Change line: `gzip -cd ../$name-$version-apng.patch.gz | patch -p0`  TO

```
patch -p0  -i ../$name-$version-apng.patch
```

2. Should also work: **add individual NOEXTRACT to patch file**

```
source=( http://downloads.sourceforge.net/$name/$name-$version.tar.xz \
	 NOEXTRACT::http://downloads.sourceforge.net/project/apng/libpng/libpng16/$name-$version-apng.patch.gz)

```

if you run `pkgmk -kw` you can afterwards inspect the workdir and check it.

**Comment by tnut** [comment]
Very nice the only think here NOEXTRACT should be NODECOMPRESS instead

2016-03-02 19:20 GMT+01:00 peter1000 <notifications@github.com>:

**Comment by tnut** [comment]
With This recept:

# Description: Libraries used by other programs for reading and writing PNG
files.
# URL: http://www.libpng.org/pub/png/libpng.html

# Packager: tnut at nutyx dot
org

# Depends
on:



name=libpng

version=1.6.21

release=1



source=( http://downloads.sourceforge.net/$name/$name-$version.tar.xz
\
         NOEXTRACT:
http://downloads.sourceforge.net/project/apng/libpng/libpng16/$name-$version-apng.patch.gz)



build()
{

cd
$name-$version

patch -p0
../$name-$version-apng.patch

# gzip -cd ../$name-$version-apng.patch.gz | patch
-p0

./configure --prefix=/usr
\

--mandir=/usr/share/man
\

--infodir=/usr/share/info
\

--disable-static

make

make DESTDIR=$PKG
install

}

When I try pkgmk -kw, I get:
==> Configuration settings...
  -> PKGMK_INSTALL:          no
  -> PKGMK_WORK_DIR:         /tmp/work
  -> PKGMK_SOURCE_DIR:       /tmp
==> WARNING: CLEAN IGNORED.
  -> PKGMK_IGNORE_REPO:      no
  -> PKGMK_IGNORE_FOOTPRINT: yes
  -> PKGMK_IGNORE_MD5SUM:    yes
  -> PKGMK_COMPRESS_PACKAGE: yes
  -> PKGMK_COMPRESSION_MODE: xz
  -> PKGMK_COMPRESSION_OPTS: -9
==> Package info...
  -> name:    libpng
  -> version: 1.6.21
  -> release: 1

====> ABORTING....
    -> Source file '/tmp/libpng-1.6.21.tar.xz' not found (use option -d to
download).
Which is wroung since the source is in  /tmp/libpng-1.6.21.tar.xz

When I try pkgmk -kw -d, I get:

==> Configuration settings...
  -> PKGMK_INSTALL:          no
  -> PKGMK_WORK_DIR:         /tmp/work
  -> PKGMK_SOURCE_DIR:       /tmp
==> WARNING: CLEAN IGNORED.
  -> PKGMK_IGNORE_REPO:      no
  -> PKGMK_IGNORE_FOOTPRINT: yes
  -> PKGMK_IGNORE_MD5SUM:    yes
  -> PKGMK_COMPRESS_PACKAGE: yes
  -> PKGMK_COMPRESSION_MODE: xz
  -> PKGMK_COMPRESSION_OPTS: -9
==> Package info...
  -> name:    libpng
  -> version: 1.6.21
  -> release: 1
==> Found  Source file     : </tmp/libpng-1.6.21.tar.xz>

====> ABORTING....
    -> The protocol: <NOEXTRACT:http> is not supported. SOURCE: <NOEXTRACT:
http://downloads.sourceforge.net/project/apng/libpng/libpng16/libpng-1.6.21-apng.patch.gz
>

**Comment by peter1000** [comment]
I'm busy a couple of days - maybe you could recheck my proposed solution - and if they work close the issue.

**Comment by peter1000** [comment]
I guess this ticket can be close for now.
