### ISSUE TITLE
new pkgmk.in does see the local source files anymore

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#49]
I have the sources already download. pkgmk keep trying to download them

**Comment by tnut** [comment]
My god the code has so much change I can't help you anymore on this

**Comment by peter1000** [comment]
will look into this issue

**Comment by peter1000** [comment]
Maybe you can recheck if this fixes it and then close the issue.

**Comment by peter1000** [comment]
I guess this ticket can be close for now.
