### ISSUE TITLE
pkgmk.in if a file in the source array variable, it doesnt find him 

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#50]
Even if the file is in place, 
I try pkgmk in os-prober:
cd /usr/ports/cli-extra/os-prober
pkgmk 
==> Configuration settings...
  -> PKGMK_INSTALL:          no
  -> PKGMK_WORK_DIR:         /tmp/work
  -> PKGMK_SOURCE_DIR:       /sources
==> WARNING: CLEAN IGNORED.
  -> PKGMK_IGNORE_REPO:      no
  -> PKGMK_IGNORE_FOOTPRINT: yes
  -> PKGMK_IGNORE_MD5SUM:    yes
  -> PKGMK_COMPRESS_PACKAGE: yes
  -> PKGMK_COMPRESSION_MODE: xz
  -> PKGMK_COMPRESSION_OPTS: -9
==> Package info...
  -> name:    os-prober
  -> version: 1.70
  -> release: 1
  -> group:   os

====> ABORTING....
    -> Local Source file '/sources/grub' not found. SOURCE: <grub>

The file is in the ports directory not in the sources directory in this case

**Comment by peter1000** [comment]
will look into this issue

**Comment by peter1000** [comment]
Maybe you can recheck if this fixes it and then close the issue.

**Comment by peter1000** [comment]
I guess this ticket can be close for now.
