### ISSUE TITLE
Cards git Example Pkgfile

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#55]
I did an example Pkgfile for cards using git version: <https://github.com/P-NuTyX/p-diverse/tree/master/cards>

If you manually set the version to e.g. `version=1.0.0`  and than compile the pkg **and afterwards reopen the Pkgfile** you will see what I meant about the function: `update_pkgver`

**Comment by tnut** [comment]
I think you should fix issues on existing features before you create new ones. At the moment the script pkgmk is not usable anymore and that's really sad

**Comment by peter1000** [comment]
The packages you mention compile here all with `pkgmk`.  Anyway it is good you reverted back to your previous version so there is no harm done as nearly all of the other stuff was contributed by me.
I will be busy a couple of days, but feel free to open an issue in case you find something else.
