### ISSUE TITLE
cards depcreate vim

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#56]
Not work with pkgmk.conf untouched
cards depcreate vim
/usr/ports/base-extra/vim has no deps
create of vim
cards create: /usr/ports/base-extra/vim package(s)
==> Configuration settings...
  -> PKGMK_INSTALL:          no
  -> PKGMK_WORK_DIR:         /usr/ports/base-extra/vim/work
  -> PKGMK_SOURCE_DIR:       /usr/ports/base-extra/vim
==> WARNING: CLEAN IGNORED.
  -> PKGMK_IGNORE_REPO:      yes
  -> PKGMK_IGNORE_FOOTPRINT: yes
  -> PKGMK_IGNORE_MD5SUM:    yes
==> <.PKGREPO> file will be deleted.
  -> PKGMK_COMPRESS_PACKAGE: no
==> Package info...
  -> name:    vim
  -> version: 7.4
  -> release: 1
==> Found  Source file     : </usr/ports/base-extra/vim/vim-7.4.tar.bz2>
==> Found  Source file     : </usr/ports/base-extra/vim/vim-7.4-locale-1.patch>
==> Building package: </usr/ports/base-extra/vim/vim1456948697i686.cards.tar.xz>
  -> Extracting file with (bsdtar): </usr/ports/base-extra/vim/vim-7.4.tar.bz2>
- build
- vimv=vim74
- cd vim74
- patch -Np1 -i /usr/ports/base-extra/vim/work/src/vim-7.4-locale-1.patch
  patch: ***\* Can't open patch file /usr/ports/base-extra/vim/work/src/vim-7.4-locale-1.patch : No such file or directory

====> ABORTING....
    -> No files found in package </usr/ports/base-extra/vim/work/pkg>

cards 1.99.5 depcreate: could not parse /usr/ports/base-extra/vim/Pkgfile

**Comment by tnut** [comment]
Here the bug is that pkgmk try to open the patch which was not move to the PKGMK_WORK_DIR/src dir. All the files located in the source array variable should be copied to the  PKGMK_WORK_DIR/src folder

**Comment by peter1000** [comment]
I'm busy a couple of days - maybe you could recheck after merging the open pullrequest - and if they work close the issue.

I did: `pkgmk`: success

**Comment by peter1000** [comment]
I guess this ticket can be close for now.
