### ISSUE TITLE
Subordinations des collections

### ISSUE THREAD

**Issue by Greg-Electric-dreams** [NuTyX/cards#6]
I still see possibly a problem with mybld, creating a personal collection may involve dependencies in "gui-extra" and "cli-extra". However, these collections are the last of the pyramid. My PKGFILES do not see the cli / gui-extra deps ...

Fr 
Je vois encore eventuellement un probleme à mybld, la création d'une collection personel peut impliqué des dépendances dans "gui-extra" et "cli-extra". Or, ces collections sont les dernières de la pyramide. Mes PKGFILES ne voient pas les deps cli/gui-extra...

**Comment by tnut** [comment]
With the last change, its now possible to make a new tree of collection dependencies via the COLLECTIONS variable.
If you put:
COLLECTIONS=(gui-extra gui cli base) in your .mybld file it should solve this issue

**Comment by Greg-Electric-dreams** [comment]
Thanks
