### ISSUE TITLE
Question: check_directory() -x

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#61]
https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L174

Just a question why do you need to check that the directories are executable?

help test:

```
-x FILE        True if the file is executable by you.
```

**Comment by tnut** [comment]
As far as I remember if you want to make a Directory own By A user but readeable by B user it has to have the -x flag

**Comment by peter1000** [comment]
Thanks
