### ISSUE TITLE
Question $group

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#64]
Just a question: https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1225

```bash
	if [ -z $group ]; then
		group="`echo $name | cut -d "-" -f1`"
	fi
	if [ "$group" == "$name" ]; then
		unset group
	fi
	if [ -z "$version" ]; then
		if [ ! -z "$group" ];then
			if [ -f ../$group/$PKGMK_PKGFILE ];then
				. ../$group/$PKGMK_PKGFILE
				unset run
				. $PKGMK_PKGFILE
			else
				warning "Variable 'version' not initiated or not found in $PKGMK_PKGFILE."
			fi
		else
			warning "Variable 'version' not initiated or not found in $PKGMK_PKGFILE."
		fi
	fi
```

This **$group** variable: comes that from Arch-PKGBUILD or from cards Pkgfiles??

Maybe you have an example somewhere - Thanks
P

**Comment by tnut** [comment]
Yeah I'm so glad you ask the question because now, all definitions are available :+1: 
Here is the one you are looking for

http://nutyx.org/en/dictionary.html#ID020

**Comment by peter1000** [comment]
Thanks - sorry I missed that ;)

**Comment by tnut** [comment]
About the dictionary.html page, don't hesitate to review it I'm shure I
made some syntax errors

2016-04-08 12:45 GMT+02:00 peter1000 <notifications@github.com>:

**Comment by peter1000** [comment]
Just skipped over it:  will send you a pull request later

**Comment by tnut** [comment]
Thanks a lot
