### ISSUE TITLE
Question: PKGMK_SPIT

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#65]
I wonder what the 'PKGMK_SPIT' does.

**It seems it is only assigned to but never used??**

https://github.com/NuTyX/cards/search?utf8=%E2%9C%93&q=PKGMK_SPIT

Maybe I miss something - or is it old unused code??

**Comment by tnut** [comment]
You right, we don't use it (yet) I took it from ARCH linux but never use it

**Comment by peter1000** [comment]
Thanks for the info
