### ISSUE TITLE
Need to know If you are interested

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#68]
Hi @tnut,

I would need some information from you.

I uploaded a first draft of [pl_bash_functions](https://github.com/P-Linux/pl_bash_functions_compatible) which is a completely rewritten bash function library I plan to use. (not finished yet - also no proper documentation)

**It is not finished yet.....**

* It **has nearly 300 test cases** already written..

* has **mostly self-contained functions** (do not require global variables) so this is quite portable.

* Supports already probably more than the have code of the current pkgmk.in

* Supports **md5sum verification for source files**

* has a good number of additional versification: e.g. entries in the source array are checked for correct syntax

*  not sure if it is faster, but **it avoids many of the external command calls**: replaces some of the grep/sed usages with bash internal syntax ..

---

My plan is to write a **new pkgmk.in** using this library and adding just some of the other things needed for the final functionality.

I will use this library also for some other things like downloading the initial source files for a chroot etc..

---

### My Question

**I plan that my fork of `cards` depends on this package**: meaning  [pl_bash_functions](https://github.com/P-Linux/pl_bash_functions) must be first installed like some other required packages e.g. 'sed or bash'.

I wrote a compatibility function to support NuTyX comment-line variables and also some of the other variable options.

Here is the QUESTION: are you interested to use something like this also for NuTyX-cards?

#### If you are interested - Yes

I can work with you to solve still some undefined issues and make it compatible with NuTyX requirements.

#### If you are NOT interested - NO

I will remove the backwards compatibility and clean things out.

Than I write a small tool to convert NuTyX-Pkgfiles to this version format.

My personal needs are a bit different than what you are doing: I need mainly to compile all from source, support probably only one light desktop like: xfce4 or lxqt.

---

Anyway, **I just need to know if you are interest to use this package as a base for a rewritten pkgmk.in?**

**Comment by peter1000** [comment]
By the way: the tests should run without installation: best in a maximazied terminal: see:  

```bash
cd pl_bash_functions/scripts/tests
bash test_all.sh
```

**Comment by tnut** [comment]
Thanks for your work. This week I'm not at home. Wll read all about this when I come back

**Comment by peter1000** [comment]
Thanks for your reply - I will add in the meantime some more - maybe even get a first new pkgmk ready till you are back.

Have a good time.

**Comment by peter1000** [comment]
Just for info: I'm write some information about every **PKGMK_** variable used. You are welcome to reuse that later for your own documentation.

**Comment by tnut** [comment]
Ok I did had time this we. Hope we can go on next week

**Comment by tnut** [comment]
I do not find the information about every PKGMK_ variable you mention

**Comment by peter1000** [comment]
> I do not find the information about every PKGMK_ variable you mention

This is not in the https://github.com/P-Linux/pl_bash_functions_compatible package but I write it for the new: **cards make command: cmk** which I hope to use instead of the Curx pkgmk.in

It is not yet uploaded but I wrote already a lot.

---

I'm adding some functionalities which I think would be nice for me to have: e.g. 
* option to path an alternate search path for the cmd-option --recursive.
* allow `cards make command (cmk): to make use of registered collections and build them in the defined order
     * specify multiple ports: cmk --portslist bash wget /absolute_path_to_other_port
* allow `cards make command (cmk): to use a file with a portslist / optional alternate collectionlist and process them in the defined order
.....
This will not be backwards compatible: For me I don't mind - I will write a small script: bash or python to convert existing NuTyX / Crux Pkgfiles.

I have started some libraries [here (nearly finished)](https://github.com/P-Linux/pl_bash_functions)

and have started the `cmk script` with the documentation but nothing uploaded yet.

Cheers
P

**Comment by peter1000** [comment]
I guess my main question for this issue is: I plan to have a a separate `bash_functions library` which must be installed before cards works.

This allows me to reuse the code for all the other things more easily and also to **test it in one place**

**Comment by peter1000** [comment]
### pl_bash_functions Release 0.9.0

Just to let you know: I uploaded the first release of: [pl_bash_functions](https://p-linux.github.io/pl_bash_functions/) 

* it has already a nice test case of: **448 tests**
* I will still add some things as I write a new cards make command script: `cmk`
* Still needs testing in a `real` user case: will do that in the `cmk` script I write.

Most of it is finished (except error fixing) and the `process_ports.sh` which I just started.
