### ISSUE TITLE
Question: PKGMK_NOSTRIP

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#70]
https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L404

**How is that supposed to work?  where is a .nostrip file created? Or do I have to create it manually?**

```
	if [ -f $PKGMK_ROOT/$PKGMK_NOSTRIP ]; then
		FILTER="grep -v -f $PKGMK_ROOT/$PKGMK_NOSTRIP"
	else
		FILTER="cat"
	fi
```

[cards/search PKGMK_NOSTRIP](https://github.com/NuTyX/cards/search?utf8=%E2%9C%93&q=PKGMK_NOSTRIP)

It looks to me that everyone handles this with setting the: PKGMK_NO_STRIP in the Pkgfile: [see](https://github.com/search?q=org%3ANuTyX+PKGMK_NO_STRIP&type=Code)

**Comment by tnut** [comment]
It should be mentionned in: man pkgmk.conf

**Comment by peter1000** [comment]
Not sure what you mean: it should mention that it needs to be manually created or something else?
Is it actually needed/used I could not find anything only: PKGMK_NO_STRIP

**Comment by tnut** [comment]
I have never use this functionnality since (almost) 10 years of NuTyX. I guess we could get read of it.
