### ISSUE TITLE
Question: Pkgfile name variable

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#71]
Just a question: Does the **Pkgfile name variable** still need to be the same as the folder of the port**

You write:

https://github.com/NuTyX/core/blob/master/www/en/dictionary.html#L114

```
The Pkgfile file must be located in a folder with the same name as the name variable 
defined in the Pkgfile.
```

https://github.com/NuTyX/core/blob/master/www/fr/dictionary.html#L132
```
Le fichier Pkgfile doit se trouver dans un dossier portant le même nom que la variable name 
définie dans ce fichier Pkgfile.
```

Questions: 

* Why must the folder be the same name?
* [The current code does not do this](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1217)

**Comment by tnut** [comment]
https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1198
And most of the scripts are using the folder name as "nameref" when they loop

**Comment by peter1000** [comment]
Thanks - I saw that - just the current code does overwrite it in seldom cases.

**Comment by tnut** [comment]
What means "seldom cases"

**Comment by peter1000** [comment]
Current situation: normally it uses the port folder name [here](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1198)

but if in the Pkgfile a variable `pkgname` is defined: most offical NuTyX use `name` than it gets overwritten with whatever is in the Pkgfile [here](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1213)

```
	if [ ! -z $pkgname ];then
		if (( ${#pkgname[@]} > 1 )); then
			PKGMK_SPIT="yes"
		else
			name=$pkgname
		fi
	fi
```

> "seldom cases"

Not very often because most NuTyX package use the variable: `name` But if I remember correctly with the last release you made a number of Arch PKGBUID variables available - so people might use them in there Pkgfiles.

---

There are a number of other things I noticed: normally a command-line option should take priority over configuration options: in pkgmk this is the opposite which I find a bit strange.

Anyway: I rewrite it.

**Comment by tnut** [comment]
I think I flag out a bug about this, but no idea how to fix it without having to rewrite everything. I think I can live with that
