### ISSUE TITLE
Suggestion : Amélioration de la commande "cards base [option]"

### ISSUE THREAD

**Issue by sh4d0w31410** [NuTyX/cards#72]
### Présentation : 

J'ai pensé à une amélioration de la commande "cards base" qui me semble pertinente.
Je souhaiterais qu'une fonctionnalité de cards soit ajoutée permettant à l'utilisateur de décider quand son système est une "base" qui lui convient, et de pouvoir revenir vers cette base en utilisant "**cards base [option]**".

### Explication : 
Par exemple, je souhaite que ma base soit : base NuTyX + xorg + lxdm + xfce4 + firefox + etc ....

Une fois l'ensemble de ces paquets installés sur la machine,  la commande "**cards base create**" devrait pouvoir faire la liste de tous les paquets installés sur le système, et les inscrire dans un fichier texte.

La commande "**cards base config**" devrait présenter les paquets enregistrés comme base.
La commande "**cards base check**" devrait lister les paquets ajoutés ou supprimés par rapport à cette base enregistrée.
J'imagine qu'avec "**cards base save**" et "**cards base remove**" l'utilisateur pourrait modifier sa base au fil du temps.

Et bien entendu, la finalité, la commande "**cards base -r _fichier.txt_**" devrait permettre de revenir vers la base choisie par l'utilisateur. A cet instant, cards devrait pouvoir ajouter et / ou supprimer les paquets pour faire revenir le système vers la base enregistrée.

Voilà mon idée, j’espère avoir réussi à vous expliquer clairement mon souhait, et à vous de décider de son utilité.

**Comment by peter1000** [comment]
hi tnut ,

If you think this is a good feature to added, maybe it would be better to add it as a *new feature*. and not intermix it with the current *base system* option

just my opinion

**Comment by tnut** [comment]
songs too complicate for me. As explain in cards base -h its just a matter of directories. No need to change that in my opiginon

**Comment by tnut** [comment]
probably add the --config <myconfigfile> to cards base would already cover a lot if cases

**Comment by tnut** [comment]
Arrrrf It's already included

cards base -h

options:
  -h, --help  	   Print this help message
  --conf=<file>    Specify alternative 'cards.conf' configuration file
  -n, --dry  	   Not doing the action. Only show (if possible) what will be done.
  --root=<path>    Specify alternative installation root
  -r, --remove     Remove the packages founds, use with care.

**Comment by peter1000** [comment]
I'm not sure if he meant that: I did a google translation.

Anyway you may want to give an example in more details (cards.conf) how he can do it 

So that he can always return to the own defined base: `base NuTyX + xorg + lxdm + xfce4 + firefox `

**Comment by tnut** [comment]
sh4d0w31410:

Si tu veux en attendant te faire une base personnalisée, c'est très simple, tu te créé un dossier par ex sous /var/lib/pkg/mabase
et ensuite si par exemple l'install actuelle doit être ta nouvelle base, tu créera un dossier par  paquet via la commande:

   for i in `cards list|cut -d " " -f1`; do mkdir /var/lib/pkg/mabase/$i;done
   echo "base /var/lib/pkg/mabase" >> /etc/cards.conf

  
et le tour est joué

**Comment by sh4d0w31410** [comment]
D'accord tnut, j'ai noté ta réponse, je vais y travailler.
En effet se créer un dossier personnalisé et rajouter l'entrée correspondante dans cards.conf produira le même effet.
Merci @peter1000 et @tnut pour vos réponses.
Je ferme donc cette issue puisque réglée.
A bientôt
