### ISSUE TITLE
Add an download option

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#77]
when 'cards download' would be possible (as an non root user) it would make possible to split the download from the upgrade process which can be done in the background while the machine is running and could be launch via a cron task. This way at shudown, cards would only need to make install the updates

**Comment by peter1000** [comment]
I did not checkout the automatic download/upgrade option: just had read it in the release note.

Just a thought: this should be configurable (maybe it is) - not all users like to automatically download things.

Just a thought.

**Comment by tnut** [comment]
It's already the case. One line in the single_init file: line24

**Comment by tnut** [comment]
Actually this feature is already implemeted:
```cards upgrade --dry```
does the job
