### ISSUE TITLE
Possible Error:  .PKGREPO

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#78]
hi I'm working on the .PKGREPO part and saw that there might be a possible error and wanted to let you know.

You check the description for your delimiter (#)  https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1035  but you do not do so for the other parts.

This could theoretically mess up your  .PKGREPO : EXAMPLE Maintainers

```
# Description: Utilities to administer the extended attributes on filesystem objects
# URL: http://savannah.nongnu.org/projects/attr
# Maintainers: peter1000 # tnut
# Packagers: pierre at nutyx dot org, tnut at nutyx dot org
````

Output
```
1462279702#.cards.tar#2.4.47#1#Utilities to administer the extended attributes on filesystem objects#http://savannah.nongnu.org/projects/attr#peter1000 # tnut#pierre at nutyx dot org, tnut at nutyx dot org

```

* Also email addresses may contain special characters see: https://en.wikipedia.org/wiki/Email_address : **Specified special characters:** `!#$%&'*+-/=?^_`{|}~`

* URL

see https://en.wikipedia.org/wiki/Fragment_identifier `The fragment identifier introduced by a hash mark # is the optional last part of a URL for a document.`

**Comment by peter1000** [comment]
Maybe escape all parts or use an other delimiter for .PKGREPO

**Comment by tnut** [comment]
I know this issue since long time, that the reason I check only the Description field at the moment.
I planning to review completly the .PKGREPO format of a collection (one info one line much more straight forward)
