### ISSUE TITLE
Question: PORT .PKGREPO file

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#79]
hi @tnut,

Just a short question.

Is there a reason you include in the PORT .PKGREPO only files which start with the port name.

[source update_repo()](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1027-1064)

* e.g. sources which might start with an other name are not included?

* if PKGMK_SOURCE_DIR is set sources are not included at all?

Seems to be not consistent... but maybe I miss something here?

What do you think: would it make sense to include only:

* package archive files
* the Pkgfile
* and the files you specified in: [add_meta_files()](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L648-668)   which are: `README, pre-install, post-install`

**Comment by peter1000** [comment]
Hi,

I'm writing together some info about the port repo file and have an additional question: Do you still remember why you only include the `Pkgfile` line if the port was not build?

I know some info is missing like build time ect. but just curious what is the reason for skipping for example any `name.README` ect..

**Comment by tnut** [comment]
This is historical reason as today cards sync do not "sync" those files anymore. It was included in the 0.x.y version of cards
