### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#81]
hi,

this part seems to me will never be called: https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1395-1396

If no Targets exist `build_needed` will always return yes: or do I miss something?

**Comment by tnut** [comment]
Check again it should be used (as far I remember at least)

**Comment by peter1000** [comment]
found something else you might want to look into in the future:

does not make any sense to me https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L828-835

seems you check that already above.

*BTW: I only point out what I see and you might be interested to improve in the future:*

**of course you are more than welcome to use my new cards make command when I finished it** :+1:

**Comment by peter1000** [comment]
seems this check should not be necessary: https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L916

Is this not already done when you call: [get_package_list](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L318-327)

**Comment by peter1000** [comment]
could not find where the file `.INFO` is coming from https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L738

Maybe it's a historical leftover?

**Comment by tnut** [comment]
yes. It doen't heart to keep it. If I change (again) my mind
