### ISSUE TITLE
possible Error:  default group is not build

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#82]
hi,

I'm not sure if it is an error but it seems that the default groups are not build.

e.g.: CARDS PKGFiLE

```
# Description: A set of utilities to manage software packages on NuTyX distribution.
# URL: https://github.com/NuTyX/cards
# Maintainer: tnut at nutyx dot org
# Packager: tnut at nutyx dot org

PKGMK_IGNORE_RUNTIMEDEPS="no"
PKGMK_GROUPS=(devel doc man)
name=cards
version=2.0
release=1

source=(http://downloads.nutyx.org/files/cards-$version.tar.gz)
build () {
cd $name-$version
make all
make DESTDIR=$PKG install
mkdir -p $PKG/{etc,usr}/ports
}
devel()
{
cd $PKG
bsdtar -cf \
$PKGMK_PACKAGE_DIR/$name.devel${PKGMK_BUILDVER}`uname -m`.$PKGMK_PACKAGE_EXT \
usr/bin \
usr/ports \
var \
etc/ports \
etc/pkgmk.conf.example
rm -rf var usr/bin usr/ports etc/pkgmk.conf.example etc/ports 
}
```

This builds also the `cards.devel1463150597x86_64.cards.tar.xz` fine.

---

But if I remove the devel function: I thought a default [pack_devel](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L562-576) function should run.

Well it does not build any  `cards.devel1463150597x86_64.cards.tar.xz` file.

e.g.: CARDS PKGFiLE

```
# Description: A set of utilities to manage software packages on NuTyX distribution.
# URL: https://github.com/NuTyX/cards
# Maintainer: tnut at nutyx dot org
# Packager: tnut at nutyx dot org

PKGMK_IGNORE_RUNTIMEDEPS="no"
PKGMK_GROUPS=(devel doc man)
name=cards
version=2.0
release=1

source=(http://downloads.nutyx.org/files/cards-$version.tar.gz)
build () {
cd $name-$version
make all
make DESTDIR=$PKG install
mkdir -p $PKG/{etc,usr}/ports
}
#devel()
#{
#cd $PKG
#bsdtar -cf \
#$PKGMK_PACKAGE_DIR/$name.devel${PKGMK_BUILDVER}`uname -m`.$PKGMK_PACKAGE_EXT \
#usr/bin \
#usr/ports \
#var \
#etc/ports \
#etc/pkgmk.conf.example
#rm -rf var usr/bin usr/ports etc/pkgmk.conf.example etc/ports 
#}
```

maybe it's just a problem on my machine (I'm not proper uptodate) or I misunderstood it - but I think it could be an error here: https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L816

because `$1` is empty called  here:  build_package https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1399

Just wanted to let you know: as I said - maybe I also misunderstood something than just close the issue.

**Comment by tnut** [comment]
It doenst because the default set of files to be pack are not existing in this case ( usr/include, usr/share/pkgconfig etc)

**Comment by peter1000** [comment]
Thanks for the info
