### ISSUE TITLE
Add Collection name to the DB

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#83]
Would be nice to have the possibility to delete a all collection (like xfce4, xfce4-extra, kde5, kde5-extra, etc) without having to modify the cards.conf file (via the base <folder> option)

It means:
- A Pkgfile have a new variable 'collection'.
- If the variable is not set in the Pkgfile (recommended), the pkgmk script will assign the parent directory name to the 'collection' variable
- The collection name will be in the meta file so that even if we use the pkgadd <archivefile>, it really use the ones define in the meta datas
- As the info is in the DB of the installed packages, it will be possible to delete a collection ... and possibly do other thinks around

**Comment by tnut** [comment]
Done

**Comment by peter1000** [comment]
hi  @tnut,

Just to clarify for me the idea behind this:

**Question:** 

---

* How does that interact with the current collections.

e.g.: 

```
special_1 :
     port1a         - Has no collection tag
     port2a         - Has a collection tag called: audio_special
     port3a         - Has a collection tag called: graphic_special
```

```
special_2 :
     port1b         - Has no collection tag
     port2b         - Has a collection tag called: audio_special
     port3b         - Has a collection tag called: graphic_special
```

* How does one register this in the cards.conf ?
* what is the command to build/install all in collection: `special_2 `
* what is the command to build/install all in collection: `graphic_special `

--
Is the collection Tag in the Pkgfile a bit similar to Arch-Linux groups?  `groups=('base-devel')` https://www.archlinux.org/packages/core/any/autoconf/

https://www.archlinux.org/pacman/PKGBUILD.5.html

```
 groups (array)

    An array of symbolic names that represent groups of packages, 
   allowing you to install multiple packages by requesting a single target. 
   For example, one could install all KDE packages by installing the kde group.
```

In that case would it not be better to ONLY use the collection tag of the Pkgfile and do not use the top parent directory at all. 
Only use the parrnt directory to register port search/build path.

**Comment by peter1000** [comment]
Maybe call the tag `pkggroup` instead of `collection`

**Comment by tnut** [comment]
The primary need I found for that is to be able to remove without extra configuration a complete collection. It's really needed for GUI like Gnome or KDE as they often change the names of the packages.

A collection is today already possible to be installed via (for kde5 collection for example) the command:

```cards install kde5```

In NuTyX, we speak about Collection, Group and Category: the difference between them is already define and quiet clear:

A Collection: http://nutyx.org/en/dictionary.html#ID010
A Group: http://nutyx.org/en/dictionary.html#ID020
A Category: http://nutyx.org/en/dictionary.html#ID030
I would like to stick to "collection" for historical reasons. Do you know the command:

```ports -u```

It's synchronise Collections of ports

The variable "group" is also available and it can be use in the case of 2 Total different named ports shared the sames attributes (sources, version, etc) but they have a completely different name (common in kde5 )

**Comment by peter1000** [comment]
I Yes I know about how cards defined the `collection` and `group` but having a extra `collection` variable is conform to the [A Collection](http://nutyx.org/en/dictionary.html#ID010) definition :+1: 

BUT it seems to mixing up the current concept of registered  `collection dir` in the cards.conf 

```
dir /usr/ports/base
dir /usr/ports/cli
dir /usr/ports/gui

## For kde5
# Comment following 2 lines
# if you don't want to install kde5
#
dir /var/lib/pkg/depotrepo/kde5-extra|http://downloads.nutyx.org
dir /var/lib/pkg/depotrepo/kde5|http://downloads.nutyx.org
```

other example
https://github.com/NuTyX/kde5#11-if-you-want-to-build-the-kde5-collection-from-the-sources

```
11. If you want to build the 'kde5' collection from the sources:

# bash scripts/kde5 -a

12. If you want to build the 'kde5-extra' collection from the sources:

``
# cd /root/kde5
# bash scripts/kde5-extra -s
# bash scripts/kde5-extra -a 

Have fun :)
```

**Comment by tnut** [comment]
I didn't want to use the info from cards.conf for several reasons. 

 - The pkgadd, pkgrm and pkginfo commands do not know about the cards.conf file (on purpose) but they want to know about the collection of the installed package
 - A package archive can be installed with pkgadd command and the archive can be "anywhere"
 - A collection of binaries ( or ports ) is continuously evaluating, but a installed package (as long it's stay installed) not evaluated much unless you updated it. Means it's important to track it's collection of origin.
  - Because the DB is tracking the collection, it will possible to have the same package name in two different collections and depending of what the user setup as collection, a
```cards upgrade``` will be able to upgrade a same package from different collection. A typical case would be ... dbus (it has one cli part and one gui part) but you can imagine the same story for many others (wirelesss tools, mp3 player, etc)

**Comment by tnut** [comment]
Most probably, we should define a RESTRICTED number of possible collections starting with what is existing at the moment and this restriction should be written in the pkgmk script and optionnaly in the pkgmk.conf file

**Comment by peter1000** [comment]
I'm not ready yet but in my rewrite of pkgmk I added an option to register `collections` (similar to what card does).

Reason being that this gives the possibility to build with just specifying the portname or fullpath.

something like this: if the full path is given that is used: otherwise it checks for it in registered collections or the current directory

`pkgmk bash python /home/collection1/wget`

**Comment by tnut** [comment]
I wonder if we soeak about the same story

**Comment by tnut** [comment]
I have been thinking a bit. I could be also a good idea to have the variable "group" included in the DB. I means why not even if both "group" and "collection" are sometimes talks about the sames packages (xfce4 is a good example). What is clear, is that a 'collection' in the DB of the installed packages should be the reflexion of a collection of binaries to reduce confusions.

**Comment by peter1000** [comment]
sorry I had a harddisk crash - Have to reinstall all.

As I wrote once before: (can't find the comment right now) I think the group concept has to be much better defined.  (meaning which variables are really shared and in which situation. 

*for myself* - I prefer a stricter concept: meaning each Pkgfile is selfsustained (I want use groups)

The general idea of collection in the DB might be a good one - to deinstall a whole collection with one command.

**Comment by tnut** [comment]
Easy all the variables from the "portName" port can be used in any "portName-subX"  ports. I know your felling about "stricter concept" but imagine that kde5 deal with 3 main groups each of them have the same url base, the same version and they are more then 20 ports in each groups ....

**Comment by tnut** [comment]
Done
