### ISSUE TITLE
QUESTION: PKGMK_GROUPS customary function

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#85]
Hi @tnut;

I'm doing some work on the `PKGMK_GROUPS` and just wanted to ask something:

Is it allowed/planned to execute customary functions: or only to overwrite the default PKGMK_GROUPS functions?

example Pkgfile

```bash
PKGMK_GROUPS=(man some_other_function)
...

build() {
...
}

some_other_function() {
    ...pack some other files or what ever

}
```

**QUESTION:** MUST a customary PKGMK_GROUPS function be named like one of the default ones: `lib devel doc man service` or ist it allowed to have any name: e.g: `some_other_function()`

**Comment by tnut** [comment]
I think it doesnt work. We would need to test

**Comment by peter1000** [comment]
I'm NOT suggesting to implement such - personally I think it should only be allowed to overwrite the default once: `lib devel doc man service`

**Comment by tnut** [comment]
works

**Comment by tnut** [comment]
Her is the test I did

Pkgfile iana-etc
I add following lines:

```
PKGMK_GROUPS=(test)
test() {
cd $PKG
mkdir test
touch test/blablab
bsdtar -cf $PKGMK_PACKAGE_DIR/$name.test${PKGMK_BUILDVER}${PKGMK_ARCH}.$PKGMK_PACKAGE_EXT \
test
rm -r test
}```

**Comment by peter1000** [comment]
Yes I know it worked, but the question is if that is an desired feature or not? 
Is that allowed/planned or is a check which raises an error forgotten.

In my opinion it should not work but raise an error.

**Comment by tnut** [comment]
I'm not agreed, flexibility is my first priority
.
