### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by peter1000** [NuTyX/cards#86]
I think you might have a bug in your `pack_` functions. In certain cases: pkgconfig information get lost.

---

If one specifies the an empty PKGMK_GROUPS=() **seems OK**

Have: **zlib1464956874x86_64.cards/usr/lib/pkgconfig/zlib.pc**

example: zlib

Pkgfile

```
# Description: Contains compression and decompression routines used by some programs.
# URL: http://www.zlib.net/
# Maintainer: Jean-loup Gailly (compression), Mark Adler (decompression)
# Packager: pierre at nutyx dot org
name=zlib
version=1.2.8
release=2

source=(http://www.zlib.net/zlib-$version.tar.xz)

PKGMK_GROUPS=()
build() {
# Vérifier si necessaire de faire les verifs du bon fonctionnement de
# glibc et du linker
if [ -L /bin/pwd ];then
    mv -v /tools/bin/{ld,ld-old}
    mv -v /tools/$(uname -m)-pc-linux-gnu/bin/{ld,ld-old}
    mv -v /tools/bin/{ld-new,ld}
    ln -sv /tools/bin/ld /tools/$(uname -m)-pc-linux-gnu/bin/ld

    gcc -dumpspecs | sed -e 's@/tools@@g'                   \
    -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
    -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' >      \
    `dirname $(gcc --print-libgcc-file-name)`/specs

    echo 'int main(){}' > dummy.c
    cc dummy.c -v -Wl,--verbose &> dummy.log
    readelf -l a.out | grep ': /lib'

    grep -o '/lib.*/crt[1in].*succeeded' dummy.log
    grep -B1 '^ /usr/include' dummy.log
    grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
    grep "/lib.*/libc.so.6 " dummy.log
    grep found dummy.log
    rm -v dummy.c a.out dummy.log
fi

cd zlib-$version
./configure --prefix=/usr
make
make check
make prefix=$PKG/usr install

mkdir -p $PKG/lib
mv -v $PKG/usr/lib/libz.so.* $PKG/lib
ln -sfv ../../lib/libz.so.$version  $PKG/usr/lib/libz.so
}
```

---

If one specifies the an empty PKGMK_GROUPS=(lib) **seems NOT OK**

**usr/lib/pkgconfig/zlib.pc** is nowhere packed

Pkgfile

```
# Description: Contains compression and decompression routines used by some programs.
# URL: http://www.zlib.net/
# Maintainer: Jean-loup Gailly (compression), Mark Adler (decompression)
# Packager: pierre at nutyx dot org
name=zlib
version=1.2.8
release=2

source=(http://www.zlib.net/zlib-$version.tar.xz)

PKGMK_GROUPS=(lib)
build() {
# Vérifier si necessaire de faire les verifs du bon fonctionnement de
# glibc et du linker
if [ -L /bin/pwd ];then
    mv -v /tools/bin/{ld,ld-old}
    mv -v /tools/$(uname -m)-pc-linux-gnu/bin/{ld,ld-old}
    mv -v /tools/bin/{ld-new,ld}
    ln -sv /tools/bin/ld /tools/$(uname -m)-pc-linux-gnu/bin/ld

    gcc -dumpspecs | sed -e 's@/tools@@g'                   \
    -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
    -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' >      \
    `dirname $(gcc --print-libgcc-file-name)`/specs

    echo 'int main(){}' > dummy.c
    cc dummy.c -v -Wl,--verbose &> dummy.log
    readelf -l a.out | grep ': /lib'

    grep -o '/lib.*/crt[1in].*succeeded' dummy.log
    grep -B1 '^ /usr/include' dummy.log
    grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
    grep "/lib.*/libc.so.6 " dummy.log
    grep found dummy.log
    rm -v dummy.c a.out dummy.log
fi

cd zlib-$version
./configure --prefix=/usr
make
make check
make prefix=$PKG/usr install

mkdir -p $PKG/lib
mv -v $PKG/usr/lib/libz.so.* $PKG/lib
ln -sfv ../../lib/libz.so.$version  $PKG/usr/lib/libz.so
}
```

**Comment by peter1000** [comment]
Possible solution might be here https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L830

Which does not make much sense to me anyway - but I also did not study all the code in greater detail  - as I rewrite the basic functionalities.

**Comment by tnut** [comment]
I think the case is wrong here. It make no sence to build the zlib.lib ONLY if we knows very followings point:

- zlib IS a lib
- zilb is part of the base system
- zlib MUST have a devel part (means headers in usr/include and a pkgconfig file)

If you intentially specify in the pkgfile:

PKGMK_GROUPS=(lib)

Either  you wanted intentionally have only the  XXX.lib (with the default contents)  and XXXX packages or the XXX base package and  your OWN lib function() means you own  XXX.lib

I have to be honest with you, I really regret that during all this time you are not actually use NuTyX and not participate in the build process of packages. It would be so much more benefit for the project. I'm really not shore what you are doing now will bring much to NuTyX.  I know it's not as sexy as what you are doing now.

**Comment by peter1000** [comment]
Maybe the example was not the best but I just wanted to point out that there is possibly an error which might of course effect other packages the same if someone defines in the config file: PKGMK_GROUPS=(lib)

I actually have NuTyX installed but you are right that at the moment I only use it as a 'normal user' for internet etc.. and I'm not participating in the build process of packages.

> It would be so much more benefit for the project. 

I'm not sure: other people do that but maybe not very many go through the code and show potential bugs.


**If you feel this kind of feedback is more maybe more distracting or irritating than helpful, I will just stop posting them - that's really completely fine with me too.** :+1:

**Comment by tnut** [comment]
I hope you can accept this kind of comment and not giving up because of that. Again, I think I was wrong it wound not be  only benefit  for NuTyX but for sure also for you.
No your comments are very usefull. It's just that it reflect you are not actually building any port. I can not force anybody to do so.
