### ISSUE TITLE
Problème de date dans les pages web crées par cards

### ISSUE THREAD

**Issue by guy2009** [NuTyX/cards#88]
Sur la page http://www.nutyx.org/fr/ 
les dates des posts du forum ne correspondent pas
aux heures des posts du forum http://forum.nutyx.org/index.php?action=recent

Il y a un décalage de 2 heures, sans doute un problème UTC / heure locale

**Comment by tnut** [comment]
C est exacte, actuellement, il faut que j'ajoute la mention UTC puisqu'il n'est pas encore possible de se connecter sur le site et de définir sa propre localisation  (comme on peut le faire sur le forum), et donc la date standard si je puis dire c'est l'heure UTC ce qui est logique en quelque sorte. Je suis actuellement avec un décalage de +7 heures. Je dois dire qu'une fois la mention UTC sera ajoutée cela devrait enlever toute confusion (comme pour la date de dernière modification des articles)
