### ISSUE TITLE
Have a shell when build fails instead of unmount and close all chroot in mybld script

### ISSUE THREAD

**Issue by rems28** [NuTyX/cards#9]
When a build fails, it can be better to start a shell in mybld chroot instead of close the entire chroot when a build fails. It can permit a Pkgfile correction to make the build successfull directly in the chroot. When the build is in good state, sync the correct Pkgfile in the git repo if it's possible.

**Comment by tnut** [comment]
I may have a solution.

**Comment by tnut** [comment]
Fixed in 2.4.139

**Comment by rems28** [comment]
Need to have a more deep work...
