### ISSUE TITLE
Uninstall lxde

### ISSUE THREAD

**Issue by grosbedos** [NuTyX/cards#90]
Hi,

When you install lxde, cards install a lot of dependencies.
When you remove lxde, cards just remove the pkg lxde. I have test with the option "-a" too.

All the dependencies keep installed.

Best regards

ps : I have tried with cards 2.2, nutyx 9.0-RC1

**Comment by tnut** [comment]
I m affraid this is a kind of a bug. lxde is a family of packages At least cards should remove all the lxde-xxx packages. Not really a big issue but should be fixed

**Comment by tnut** [comment]
Fixed in last  version
