### ISSUE TITLE
Problème de rafraîchissement d'affichage. 

### ISSUE THREAD

**Issue by Sipomatadorducosmos** [NuTyX/cards#93]
Petit problème d'affichage lors de la superposition de fenêtre.
Les couleur disparaissent lorsqu'une fenêtre passe sur FLcards ou des morceau de fenêtre tiers reste incruster sur FLcards.

Le problème disparaît lors d'une manipulation de la fenêtre FLcards

Environnement en GTK3 (Mate et Lxde)

**Comment by Artemia76** [comment]
Je n'ai pas réussi à reproduire le bug avec ma nutyx mate. S'agit il d'un type particulier d'application ? VLC , ou autre disposant d'un rendu composite ou opengl?
